Repository kubernetes/cloud-provider-gcp, pull requests merged in 2018-07, with the labels that each got.

#24 continue to publish ExternalID to fix logmon
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/OWNERS
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/controller.go
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  cmd/gcp-controller-manager/app/gke_signer.go
  cmd/gcp-controller-manager/app/gke_signer_test.go
  cmd/gcp-controller-manager/app/node_annotater.go
  cmd/gcp-controller-manager/app/node_annotater_test.go
  cmd/gcp-controller-manager/app/options.go
  cmd/gcp-controller-manager/main.go
  tools/env.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#25 Add GCB config for gke-exec-auth-plugin
  cmd/gke-exec-auth-plugin/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#28 Add metrics to cert controller
  Gopkg.lock
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_signer.go
  cmd/gcp-controller-manager/main.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 Check EK cert against root CA
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/ca_cache.go
  cmd/gcp-controller-manager/app/ca_cache_test.go
  cmd/gcp-controller-manager/app/gke_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#30 Rotate kubelet certs after 10 days
  cmd/gke-exec-auth-plugin/cache.go
  tools/env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 factor out annotaters so we can add more
  cmd/gcp-controller-manager/app/controller.go
  cmd/gcp-controller-manager/app/node_annotater.go
  cmd/gcp-controller-manager/app/node_annotater_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#31 Add label per approval type to approver metrics
  cmd/gcp-controller-manager/app/gke_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 switch owners and reviewers for gcp-controller-manager
  cmd/gcp-controller-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#32 Read VM identity from AIK cert
  cmd/gcp-controller-manager/app/gke_approver.go
  pkg/nodeidentity/id.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#36 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#34 Refactor gcp-controller-manager startup
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/controller.go
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  cmd/gcp-controller-manager/app/gke_signer.go
  cmd/gcp-controller-manager/app/gke_signer_test.go
  cmd/gcp-controller-manager/app/loops.go
  cmd/gcp-controller-manager/app/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#39 Simplify image publishing script
  README.md
  cmd/gke-exec-auth-plugin/cloudbuild.yaml
  tools/def.bzl
  tools/env.sh
  tools/workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#37 Enable node pool check
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  cmd/gcp-controller-manager/app/loops.go
  cmd/gcp-controller-manager/app/node_annotater.go
  cmd/gcp-controller-manager/app/options.go
  cmd/gke-exec-auth-plugin/cache.go
  pkg/nodeidentity/id.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#45 only reconcile labels when kube-labels instance metadata is present
  cmd/gcp-controller-manager/app/node_annotater.go
  cmd/gcp-controller-manager/app/node_annotater_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
