Repository kubernetes/cloud-provider-gcp, pull requests merged in 2018-12, with the labels that each got.

#64 bump bazel rules to fix http_archive deprecation
  BUILD
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#65 Cherrypick #64 into release-1.11.0
  BUILD
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#66 Cherrypick #64 into release-1.11.2
  BUILD
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#63 ensure Node matches metadata before approving CSRs
  WORKSPACE
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Cherry-pick "ensure Node matches metadata before approving CSRs"
  WORKSPACE
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#67 Cherry-pick "ensure Node matches metadata before approving CSRs"
  WORKSPACE
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#69 Move tools/bazel.rc to .bazelrc
  .bazelrc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#70 Move tools/bazel.rc to .bazelrc
  .bazelrc
Labels: approved, cncf-cla: yes, lgtm, size/XS
