Repository kubernetes/cloud-provider-gcp, pull requests merged in 2018-06, with the labels that each got.

#20 Make exec plugin more robust
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/cache.go
  cmd/gke-exec-auth-plugin/main.go
  cmd/gke-exec-auth-plugin/request.go
  cmd/gke-exec-auth-plugin/request_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#19 Add leader election to gke-certificates-controller.
  Gopkg.lock
  cmd/gke-certificates-controller/app/BUILD
  cmd/gke-certificates-controller/app/gke_certificates_controller.go
  cmd/gke-certificates-controller/app/options.go
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/types.go
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1/types.go
  vendor/k8s.io/client-go/tools/leaderelection/BUILD
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/BUILD
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/register.go
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/types.go
  vendor/k8s.io/kubernetes/pkg/apis/componentconfig/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/BUILD
  vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#22 Use dedicated clients for informer/approver/signer
  cmd/gke-certificates-controller/app/gke_certificates_controller.go
  tools/env.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
