Repository kubernetes/cloud-provider-gcp, pull requests merged in 2018-08, with the labels that each got.

#46 adding code-of-conduct.md
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#47 Retry CSR failing due to transient errors
  Gopkg.lock
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#48 Fix prometheus metric names to follow the style guide
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_signer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#43 Tests for plugin caching logic
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/cache.go
  cmd/gke-exec-auth-plugin/cache_test.go
  cmd/gke-exec-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Unit tests for gke_approver validation
  Gopkg.lock
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/ca_cache_test.go
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  pkg/nodeidentity/id.go
  vendor/github.com/google/go-tpm/tpm2/constants.go
  vendor/github.com/google/go-tpm/tpm2/structures.go
  vendor/github.com/google/go-tpm/tpm2/tpm2.go
  vendor/github.com/google/go-tpm/tpmutil/BUILD
  vendor/github.com/google/go-tpm/tpmutil/run.go
  vendor/github.com/google/go-tpm/tpmutil/run_linux.go
  vendor/github.com/google/go-tpm/tpmutil/run_windows.go
  vendor/github.com/google/go-tpm/tpmutil/tbs/BUILD
  vendor/github.com/google/go-tpm/tpmutil/tbs/tbs_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#51 Re-run gazelle and add gazelle-diff command for presubmit
  BUILD
  cmd/gcp-controller-manager/app/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S
