Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-04, with the labels that each got.

#85 Use cluster's location when fetching from GKE API
  WORKSPACE
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  cmd/gcp-controller-manager/app/options.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#87 Fix startup and CSRs for regional clusters
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/gke_approver_test.go
  cmd/gcp-controller-manager/app/options.go
  cmd/gcp-controller-manager/app/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#88 Don't re-queue deleted nodes in nodeAnnotator
  cmd/cloud-controller-manager/BUILD
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/node_annotater.go
  cmd/gcp-controller-manager/app/node_annotater_test.go
  cmd/gke-exec-auth-plugin/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/L

#89 Updated dependencies and fix README
  README.md
  go.mod
  go.sum
  vendor/k8s.io/client-go/pkg/version/base.go
  vendor/k8s.io/kubernetes/pkg/version/base.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#90 Filesystem lock for gke-exec-auth-plugin
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/main.go
  go.mod
  go.sum
  vendor/github.com/gofrs/flock/.gitignore
  vendor/github.com/gofrs/flock/.travis.yml
  vendor/github.com/gofrs/flock/BUILD
  vendor/github.com/gofrs/flock/LICENSE
  vendor/github.com/gofrs/flock/README.md
  vendor/github.com/gofrs/flock/appveyor.yml
  vendor/github.com/gofrs/flock/flock.go
  vendor/github.com/gofrs/flock/flock_unix.go
  vendor/github.com/gofrs/flock/flock_winapi.go
  vendor/github.com/gofrs/flock/flock_windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#91 Moved lockfile from os's tmp to cache dir.
  cmd/gke-exec-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
