Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-12, with the labels that each got.

#122 Clean up a few staticcheck findings
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gke-exec-auth-plugin/alt_token_source.go
  cmd/gke-exec-auth-plugin/cache.go
  cmd/gke-exec-auth-plugin/tpm.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#119 Don't set a timeout on informers in gcp-controller-manager
  cmd/gcp-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#123 Node syncer
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/hms.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/node_syncer.go
  cmd/gcp-controller-manager/node_syncer_test.go
  cmd/gcp-controller-manager/service_account_verifier_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#124 Pin distroless/static image to a tag instead of latest
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS
