Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-10, with the labels that each got.

#109 gcp-controller-manager: clean up startup SAR error metric noise
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/main.go
  go.mod
  pkg/csrmetrics/csrmetrics.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#110 Update numerous toolchain components.
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#111 Improve CSR metric reporting
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_approver_test.go
  cmd/gcp-controller-manager/csr_signer.go
  cmd/gcp-controller-manager/csr_signer_test.go
  cmd/gcp-controller-manager/loops.go
  pkg/csrmetrics/csrmetrics.go
Labels: approved, cncf-cla: yes, lgtm, size/L
