Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-07, with the labels that each got.

#102 Pkg csrutil
  .bazelrc
  WORKSPACE
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_signer.go
  pkg/csrapproval/BUILD
  pkg/csrapproval/csrapproval.go
  pkg/csrapproval/csrapproval_test.go
  pkg/csrmetrics/BUILD
  pkg/csrmetrics/csrmetrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#105 merge_licenses.sh: Include own LICENSE
  tools/merge_licenses.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#106 Rename build/ to release/
  release/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/XS
