Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-11, with the labels that each got.

#117 don't let kubelets request certs with email address or URI SANs
  cmd/gcp-controller-manager/csr_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#118 Let CA file path be set via kube-env to enable Windows paths.
  cmd/gke-exec-auth-plugin/request.go
  cmd/gke-exec-auth-plugin/request_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#121 Add service-account-verifier control loop to gcp-controller-manager.
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/hms.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/sa_map.go
  cmd/gcp-controller-manager/service_account_verifier.go
  cmd/gcp-controller-manager/service_account_verifier_test.go
  go.sum
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL
