Repository kubernetes/cloud-provider-gcp, pull requests merged in 2019-05, with the labels that each got.

#94 Add a flag to disable legacy kubelet bootstrap
  cmd/gcp-controller-manager/app/controller.go
  cmd/gcp-controller-manager/app/gke_approver.go
  cmd/gcp-controller-manager/app/loops.go
  cmd/gcp-controller-manager/app/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#93 Remove VM identity doc mode from exec plugin
  cmd/gke-exec-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#95 gcp-controller-manager refactor part 1
  WORKSPACE
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/app/BUILD
  cmd/gcp-controller-manager/app/controller.go
  cmd/gcp-controller-manager/ca_cache.go
  cmd/gcp-controller-manager/ca_cache_test.go
  cmd/gcp-controller-manager/csrmetrics/BUILD
  cmd/gcp-controller-manager/csrmetrics/csrmetrics.go
  cmd/gcp-controller-manager/gcp_config.go
  cmd/gcp-controller-manager/gcp_config_test.go
  cmd/gcp-controller-manager/gke_approver.go
  cmd/gcp-controller-manager/gke_approver_test.go
  cmd/gcp-controller-manager/gke_signer.go
  cmd/gcp-controller-manager/gke_signer_test.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_annotater.go
  cmd/gcp-controller-manager/node_annotater_test.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/logs/BUILD
  vendor/k8s.io/kubernetes/pkg/kubectl/util/logs/logs.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#96 gcp-controller-manager refactor part 2
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_approver_test.go
  cmd/gcp-controller-manager/csr_signer.go
  cmd/gcp-controller-manager/csr_signer_test.go
  cmd/gcp-controller-manager/gcp_config.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#97 Disabled dynamic linking of gke-exec-auth-plugin binary.
  cmd/gke-exec-auth-plugin/BUILD
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#98 Update go-tpm version
  cmd/gcp-controller-manager/BUILD
  cmd/gke-exec-auth-plugin/BUILD
  go.mod
  go.sum
  vendor/github.com/google/go-tpm/tpm2/BUILD
  vendor/github.com/google/go-tpm/tpm2/README.md
  vendor/github.com/google/go-tpm/tpm2/constants.go
  vendor/github.com/google/go-tpm/tpm2/error.go
  vendor/github.com/google/go-tpm/tpm2/kdf.go
  vendor/github.com/google/go-tpm/tpm2/structures.go
  vendor/github.com/google/go-tpm/tpm2/tpm2.go
  vendor/github.com/google/go-tpm/tpmutil/BUILD
  vendor/github.com/google/go-tpm/tpmutil/encoding.go
  vendor/github.com/google/go-tpm/tpmutil/poll_other.go
  vendor/github.com/google/go-tpm/tpmutil/poll_unix.go
  vendor/github.com/google/go-tpm/tpmutil/run.go
  vendor/github.com/google/go-tpm/tpmutil/run_linux.go
  vendor/github.com/google/go-tpm/tpmutil/run_other.go
  vendor/github.com/google/go-tpm/tpmutil/run_windows.go
  vendor/github.com/google/go-tpm/tpmutil/structures.go
  vendor/github.com/google/go-tpm/tpmutil/tbs/tbs_windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#99 Allow override GCE Endpoint in gcp-controller-manager
  cmd/gcp-controller-manager/gcp_config.go
  cmd/gcp-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S
