Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-07, with the labels that each got.

#156 Remove inactive members from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 Updated rules_docker to latest to fix build error
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#149 Make node annotator failure retry correctly follow queue rate limiter
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
  cmd/gcp-controller-manager/node_syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
