Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-05, with the labels that each got.

#150 Added k8s admin account to the master.
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 Add logdump for e2e create.
  cluster/log-dump/log-dump.sh
  cluster/log-dump/logexporter-daemonset.yaml
  test/OWNERS
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#151 Fix CCM image.
  cluster/addons/cloud-controller-manager/cloud-node-controller-role.yaml
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure-kubeapiserver.sh
  cluster/gce/manifests/cloud-controller-manager.manifest
  defs/container.bzl
  deploy/cloud-controller-manager.manifest
  deploy/cloud-node-controller-role.yaml
  release/BUILD
  tools/version.sh
  tools/workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
