Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-04, with the labels that each got.

#146 Fix missing sha reference in cluster-up.
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
  release/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/M

#147 Add Ben and Amit to Clusters owners file.
  cluster/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#144 Add basic cluster up/down e2e test.
  cluster/gce/gci/configure.sh
  cluster/gce/util.sh
  test/boskos.sh
  test/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
