Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-03, with the labels that each got.

#135 Add /healthz endpoint to gcp-controller-manager
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/healthz/BUILD
  cmd/gcp-controller-manager/healthz/healthz.go
  cmd/gcp-controller-manager/healthz/healthz_test.go
  cmd/gcp-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#136 Remove awly from OWNERS and SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
  cmd/gcp-controller-manager/OWNERS
  cmd/gke-exec-auth-plugin/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 Use three-way-merge to reconcile labels from GCE instance to K8S node
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
