Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-10, with the labels that each got.

#163 Release 1.1.5 build fix
  WORKSPACE
Labels: approved, cncf-cla: yes, size/S

#164 more release-1.1.15 build fixes
  defs/container.bzl
Labels: approved, cncf-cla: yes, size/XS

#167 Sort imports after upgrade to v1.19
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/controller-manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#169 Add klog.InitFlags to correctly handle klog flags.
  cmd/gke-exec-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
