Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-02, with the labels that each got.

#131 add bazel version for bazelisk
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/XS

#134 Revert "add bazel version for bazelisk"
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/XS

#127 Allow override of image registry with IMAGE_REGISTRY env var
  README.md
  defs/container.bzl
  tools/workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#133 Change verified-ksa-to-gsa ConfigMap data encoding.
  cmd/gcp-controller-manager/sa_map.go
  cmd/gcp-controller-manager/service_account_verifier_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
