Repository kubernetes/cloud-provider-gcp, pull requests merged in 2020-06, with the labels that each got.

#152 Fix shellcheck failure in cluster/gce/config-default.sh
  cluster/gce/config-default.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#153 verify-kube-binaries uses relative path instead of fixed
  cluster/common.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#154 Create the bucket for tars based on $PROJECT
  cluster/gce/util.sh
  test/boskos.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#155 Ignore meaningless failures when setting bucket ACLs during kube-up.sh
  cluster/gce/util.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
