Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-09, with the labels that each got.

#268 Changes to support IPv6 addresses on nodes
  providers/gce/gce.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#249 replace gcr.io/gke-release to use the community registry for nvidia-gpu-device-plugin
  cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 Drop end of sunrpc port range to avoid port conflicts
  cluster/gce/gci/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#271 Create the firewall api directory
  pkg/apis/firewall/register.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test
