Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-11, with the labels that each got.

#282 Use Alpha Compute API only in case of dual stack
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#265 install pd-csi driver by default at kube-up
  cluster/addons/pdcsi-driver/README.md
  cluster/addons/pdcsi-driver/pd-csi-psp.yaml
  cluster/addons/pdcsi-driver/pd-csi-rbac.yaml
  cluster/addons/pdcsi-driver/pd-csi.yaml
  cluster/addons/pdcsi-driver/sc-premium.yaml
  cluster/addons/pdcsi-driver/sc-standard.yaml
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/manifests/BUILD
  cluster/gce/manifests/pdcsi-controller.yaml
  cluster/gce/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test

#285 Add 3-way merge for node taints
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#283 Prevent CCM from receiving feature gates it doesn't support
  cluster/gce/config-default.sh
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#290 don't expand $(ls -A /scrub) in PV_RECYCLER_TEMPLATE
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#287 Fix service BasePath
  providers/gce/gce.go
Labels: approved, cncf-cla: yes, lgtm, size/S
