Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-12, with the labels that each got.

#295 Log feature gates that did not pass through the GCP feature gate filter
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Update dependencies to match the destination version
  cmd/gcp-controller-manager/BUILD
  crd/apis/gcpfirewall/v1alpha1/zz_generated.deepcopy.go
  crd/client/gcpfirewall/clientset/versioned/BUILD
  crd/client/gcpfirewall/clientset/versioned/fake/BUILD
  crd/client/gcpfirewall/clientset/versioned/fake/clientset_generated.go
  crd/client/gcpfirewall/clientset/versioned/scheme/BUILD
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1alpha1/BUILD
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1alpha1/fake/BUILD
  crd/config/crds/networking.gke.io_gcpfirewalls.yaml
  crd/go.mod
  crd/go.sum
  crd/hack/boilerplate.go.txt
  crd/hack/update-codegen.sh
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#296 Switch the errors to warnings that are expected on first run.
  cmd/gke-exec-auth-plugin/cache.go
  cmd/gke-exec-auth-plugin/tpm.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
