Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-05, with the labels that each got.

#213 Switch to Authorization v1
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_approver_test.go
  pkg/csrapproval/BUILD
  pkg/csrapproval/csrapproval.go
  pkg/csrapproval/csrapproval_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#205 Add verify-all.sh
  tools/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#217 Add Go code coverage script
  tools/coverage/golang_coverage.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#219 Remove invalid options from CCM manifest
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#218 Remove redundant dir from golint check
  tools/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 if one node pool is broken, keep checking others to find an instance …
  cmd/gcp-controller-manager/csr_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#222 gcp-controller-manager: Fix startup panic
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#225 do a readonly install of golint for tools/verify-golint.sh
  tools/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 Use at minimum n1-standard-2 in cluster/gce/config-common.sh
  cluster/gce/config-common.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#229 Sync //providers dependencies version with k/k
  cluster/gce/gci/BUILD
  go.mod
  go.sum
  providers/go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Update gcp auth provider config
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#237 fix image tag derivation
  tools/workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
