Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-04, with the labels that each got.

#197 Adding go fmt checking script
  cmd/gcp-controller-manager/csr_signer_test.go
  cmd/gcp-controller-manager/service_account_verifier_test.go
  tools/update-gofmt.sh
  tools/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#201 Fix golint issues in credential provider
  cmd/auth-provider-gcp/app/getcredentials.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#189 Windows crossbuild support
  README.md
  WORKSPACE
  release/BUILD
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#200 Add verify-govet.sh
  cmd/auth-provider-gcp/provider/provider.go
  cmd/gcp-controller-manager/ca_cache_test.go
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_approver_test.go
  cmd/gcp-controller-manager/hms.go
  cmd/gke-exec-auth-plugin/main.go
  tools/verify-govet.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#192 Document how to re-gen BUILD files in README.md
  README.md
  tools/update_bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#208 Set user agent for GCE and GKE API clients
  cmd/gcp-controller-manager/gcp_config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#209 Add soft link to providers
  cmd/cloud-controller-manager/BUILD
  cmd/gcp-controller-manager/BUILD
  go.mod
  go.sum
  tools/update_vendor.sh
  vendor/k8s.io/cloud-provider-gcp/providers
  vendor/k8s.io/cloud-provider-gcp/providers/gce/BUILD
  vendor/k8s.io/cloud-provider-gcp/providers/gce/OWNERS
  vendor/k8s.io/cloud-provider-gcp/providers/gce/doc.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_address_manager.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_addresses.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_alpha.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_annotations.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_backendservice.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_cert.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_clusterid.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_clusters.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_disks.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_fake.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_firewall.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_forwardingrule.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_healthchecks.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_instancegroup.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_instances.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_interfaces.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_loadbalancer.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_loadbalancer_external.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_loadbalancer_internal.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_loadbalancer_metrics.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_loadbalancer_naming.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_networkendpointgroup.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_routes.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_securitypolicy.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_targetpool.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_targetproxy.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_tpu.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_urlmap.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_util.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/gce_zones.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/metrics.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/support.go
  vendor/k8s.io/cloud-provider-gcp/providers/gce/token_source.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#181 Disable local loopback for volume host
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS
