Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-06, with the labels that each got.

#239 Format the projectID for Domain-scoped project
  cmd/gcp-controller-manager/csr_approver.go
  cmd/gcp-controller-manager/csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#184 Add vinayakankugoyal as approver and reviewer of gcp-controller-manag…
  cmd/gcp-controller-manager/OWNERS
  cmd/gke-exec-auth-plugin/OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#235 Set CacheKeyType on credential provider response
  cmd/auth-provider-gcp/provider/provider.go
  cmd/auth-provider-gcp/provider/provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#241 Use versioned credential provider API
  cmd/auth-provider-gcp/app/BUILD
  cmd/auth-provider-gcp/app/getcredentials.go
  cmd/auth-provider-gcp/provider/BUILD
  cmd/auth-provider-gcp/provider/provider.go
  cmd/auth-provider-gcp/provider/provider_test.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/BUILD
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/doc.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/register.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/types.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/zz_generated.defaults.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#243 Migrate csrapproval library to certificates/v1
  pkg/csrapproval/BUILD
  pkg/csrapproval/csrapproval.go
  pkg/csrapproval/csrapproval_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
