Repository kubernetes/cloud-provider-gcp, pull requests merged in 2021-07, with the labels that each got.

#242 Add a binary kubectl-gke-exec-auth-plugin
  cmd/kubectl-gke-exec-auth-plugin/BUILD
  cmd/kubectl-gke-exec-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#246 Use node's (not cluster's) location in syncNode to support Direct-Path in regional clusters
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/node_syncer.go
  cmd/gcp-controller-manager/node_syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#252 use dl.k8s.io where possible
  cluster/common.sh
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure.sh
  cluster/gce/upgrade.sh
  cluster/gce/util.sh
  cluster/get-kube-binaries.sh
  cluster/get-kube.sh
  defs/repo_rules.bzl
Labels: approved, cncf-cla: yes, lgtm, size/M

#250 Gke gcloud auth plugin
  cmd/gke-gcloud-auth-plugin/BUILD
  cmd/gke-gcloud-auth-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, ok-to-test, size/XS

#256 A few build cleanups
  .bazelrc
  cmd/gke-gcloud-auth-plugin/BUILD
  defs/version.bzl
  tools/version.sh
  tools/workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#248 add signer for istiod after 1.22
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_signer.go
  cmd/gcp-controller-manager/istiod_csr_approver.go
  cmd/gcp-controller-manager/istiod_csr_approver_test.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#254 pkg/csrapproval: fix setting required fields
  cmd/gke-gcloud-auth-plugin/BUILD
  pkg/csrapproval/BUILD
  pkg/csrapproval/csrapproval.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#227 bump to go1.16
  WORKSPACE
  go.mod
  providers/go.mod
  tools/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
