Repository kubernetes/cloud-provider-gcp, pull requests merged in 2022-12, with the labels that each got.

#413 Add EnableMulticastAnnotationKey and value
  crd/apis/network/v1/annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#412 Fix GKENetworkParams pluralization
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/network_client.go
  crd/client/network/informers/externalversions/generic.go
  crd/client/network/informers/externalversions/network/v1/gkenetworkparams.go
  crd/client/network/informers/externalversions/network/v1/interface.go
  crd/client/network/listers/network/v1/gkenetworkparams.go
  crd/hack/update-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#415 Fix GKENetworkParams client asking for namespace. (Resource is cluster wide)
  crd/apis/network/v1/gkenetworkparams_types.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/network_client.go
  crd/client/network/informers/externalversions/network/v1/gkenetworkparams.go
  crd/client/network/informers/externalversions/network/v1/interface.go
  crd/client/network/listers/network/v1/expansion_generated.go
  crd/client/network/listers/network/v1/gkenetworkparams.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#425 Add missing v1.25.5 bump
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#427 Add script to verify if repository is up to date
  tools/verify-up-to-date.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#424 Automate cloud-controller-image-creation based on cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#428 Improve logging message of tools/verify-up-to-date.sh
  tools/verify-up-to-date.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 Add /crd to .bazelignore
  .bazelignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#408 Restore serviceAccountVerifier workers to 3 and nodeSyncer to 30 from 20
  cmd/gcp-controller-manager/loops.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#392 Update bazel image rules
  WORKSPACE
  defs/container.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#429 use a more meaninful tag and publish :latest image
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#430 Fix crd broken BUILD file
  .bazelignore
  crd/apis/network/v1/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S

#432 Cloudbuild iterations
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#435 add permissions for patch node to cloud-controller-manager
  deploy/cloud-node-controller-role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#411 Use instance ListReferrers method to check cluster membership.
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#420 Update node annotations for multi-networking
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, ok-to-test

#436 Fix incorrect return value ordering in validateInstanceGroupHint.
  cmd/gcp-controller-manager/node_csr_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#437 Fix referrer url and instance group url comparison.
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#440 Add 'cluster/bin' to '.gitignore'
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#441 Bump bazel to 5.4.0
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/XS

#439 Fix log verbosity and add additional logging.
  cmd/gcp-controller-manager/node_csr_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
