Repository kubernetes/cloud-provider-gcp, pull requests merged in 2022-11, with the labels that each got.

#385 Added clearStalePodsOnNodeRegistration flag to guard removal of pods bound to preemptible node
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#391 Define north-interface annotation.
  crd/apis/network/v1/annotations.go
  crd/apis/network/v1/annotations_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#387 Add GKENetworkParams crd
  crd/apis/network/v1/BUILD
  crd/apis/network/v1/gkenetworkparams_types.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/config/crds/networking.gke.io_gkenetworkparams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#390 Changes for fetching the subnetworks.
  providers/gce/BUILD
  providers/gce/gce_subnetworks.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#395 Introduce prefixLengthV4 attribute to l2Network
  crd/apis/network/v1/network_types.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/config/crds/networking.gke.io_networks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#397 Add test parameters that were dropped during bumping
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#400 Add response message in kubelet_readonly_csr_approver.go
  cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#403 add aojea to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#402 Pass CLOUD_PROVIDER_FLAG and set DisableKubeletCloudCredentialProviders
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#396 fix minor bug in GKENetworkParams crd
  crd/apis/network/v1/gkenetworkparams_types.go
  crd/config/crds/networking.gke.io_gkenetworkparams.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash, ok-to-test

#401 Add generated client/informer/listers for Network & GkeNetworkParams CRDs
  crd/apis/network/v1/BUILD
  crd/apis/network/v1/doc.go
  crd/apis/network/v1/gkenetworkparams_types.go
  crd/apis/network/v1/groupversion_info.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/apis/network/v1/zz_generated.register.go
  crd/client/network/clientset/versioned/BUILD
  crd/client/network/clientset/versioned/clientset.go
  crd/client/network/clientset/versioned/doc.go
  crd/client/network/clientset/versioned/fake/BUILD
  crd/client/network/clientset/versioned/fake/clientset_generated.go
  crd/client/network/clientset/versioned/fake/doc.go
  crd/client/network/clientset/versioned/fake/register.go
  crd/client/network/clientset/versioned/scheme/BUILD
  crd/client/network/clientset/versioned/scheme/doc.go
  crd/client/network/clientset/versioned/scheme/register.go
  crd/client/network/clientset/versioned/typed/network/v1/BUILD
  crd/client/network/clientset/versioned/typed/network/v1/doc.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/BUILD
  crd/client/network/clientset/versioned/typed/network/v1/fake/doc.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparamslist.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_networkinterface.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_networkinterfacelist.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_networklist.go
  crd/client/network/clientset/versioned/typed/network/v1/generated_expansion.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparams.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparamslist.go
  crd/client/network/clientset/versioned/typed/network/v1/network.go
  crd/client/network/clientset/versioned/typed/network/v1/network_client.go
  crd/client/network/clientset/versioned/typed/network/v1/networkinterface.go
  crd/client/network/clientset/versioned/typed/network/v1/networkinterfacelist.go
  crd/client/network/clientset/versioned/typed/network/v1/networklist.go
  crd/client/network/informers/externalversions/BUILD
  crd/client/network/informers/externalversions/factory.go
  crd/client/network/informers/externalversions/generic.go
  crd/client/network/informers/externalversions/internalinterfaces/BUILD
  crd/client/network/informers/externalversions/internalinterfaces/factory_interfaces.go
  crd/client/network/informers/externalversions/network/BUILD
  crd/client/network/informers/externalversions/network/interface.go
  crd/client/network/informers/externalversions/network/v1/BUILD
  crd/client/network/informers/externalversions/network/v1/gkenetworkparams.go
  crd/client/network/informers/externalversions/network/v1/interface.go
  crd/client/network/informers/externalversions/network/v1/network.go
  crd/client/network/informers/externalversions/network/v1/networkinterface.go
  crd/client/network/listers/network/v1/BUILD
  crd/client/network/listers/network/v1/expansion_generated.go
  crd/client/network/listers/network/v1/gkenetworkparams.go
  crd/client/network/listers/network/v1/network.go
  crd/client/network/listers/network/v1/networkinterface.go
  crd/hack/update-codegen.sh
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test

#406 Get namespace from service account
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go
  cmd/gcp-controller-manager/kubelet_readonly_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#409 Add a utility method to fetch compute instance
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#405 Add README file for clientauthplugin
  pkg/clientauthplugin/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test
