Repository kubernetes/cloud-provider-gcp, pull requests merged in 2022-03, with the labels that each got.

#318 Bump version.sh
  tools/version.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 Add jprzychodzen to OWNERS as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#322 Remove taints re-application from node annotator
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#325 Update clientauthentication apis from v1alpha1 to v1beta1 in gke-exec-auth-plugin
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/main.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S
