Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-05, with the labels that each got.

#528 Add unit test for cloud version of updateCIDRAllocation.
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L

#525 Update go SDK to 1.19.9 as 1.19.6 has vulnerabilities
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#531 Adding API support for nic-info annotation
  crd/apis/network/v1/annotations.go
  crd/apis/network/v1/annotations_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#512 Centralize Node patching in ipam controller.
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
  pkg/util/node/BUILD
  pkg/util/node/node.go
  pkg/util/node/node_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, sig/network

#536 Add more GNP validations to specification
  crd/apis/network/v1/gkenetworkparamset_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#537 use the tag version to build the images
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#475 don't process unsupported loadbalancers with mixed protocols
  providers/gce/BUILD
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_test.go
  providers/gce/gce_util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#534 add multinetworking node count metric in IPAM controller
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_metrics.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/XL, ok-to-test

#541 Add GNP Delete Handling
  pkg/controller/gkenetworkparamset/BUILD
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#543 Adding GNP object count metric
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#540 fix: use dl.k8s.io, not kubernetes-release bucket
  cluster/common.sh
  cluster/gce/gci/configure.sh
  cluster/gce/upgrade.sh
  cluster/gce/util.sh
  cluster/get-kube-binaries.sh
  cluster/get-kube.sh
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/cleanup

#545 build all projects in the repo
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#539 Modify Multi-network annotation generation.
  crd/apis/network/v1/network_types.go
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/XL, ok-to-test

#547 Build auth-provider-gcp binary
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#548 fix cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#549 build auth binaries publish controller images
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#550 Update cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#552 use the direct path to the artificats
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#553 Add missing network condition reasons & omitempty devicemode
  crd/apis/network/v1/gkenetworkparamset_types.go
  crd/apis/network/v1/network_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#555 Fix various GNP controller bugs
  deploy/cloud-node-controller-role.yaml
  go.mod
  go.sum
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/gkenetworkparamset_types.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/network_types.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test
