Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-04, with the labels that each got.

#503 Duplicate DPWI Related Code into a new folder dpwi as Refactor Preparation
  cmd/gcp-controller-manager/dpwi/configmap/BUILD
  cmd/gcp-controller-manager/dpwi/configmap/configmap.go
  cmd/gcp-controller-manager/dpwi/hms/BUILD
  cmd/gcp-controller-manager/dpwi/hms/hms.go
  cmd/gcp-controller-manager/dpwi/serviceaccounts/BUILD
  cmd/gcp-controller-manager/dpwi/serviceaccounts/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test

#504 Add LocalZone and Regional getters
  providers/gce/gce.go
  providers/gce/gce_fake.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#513 Bump repository to 1.26.4
  WORKSPACE
  cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml
  cluster/gce/manifests/konnectivity-server.yaml
  cluster/get-kube.sh
  ginko-test-package-version.env
  go.mod
  go.sum
  providers/go.mod
  providers/go.sum
  tools/version.sh
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/BUILD
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/registry/rest/rest.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/ready.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/cached/memory/BUILD
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/controller-manager/app/serve.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm

#515 Remove jpbetz from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#509 Add InUse function to Network object.
  crd/apis/network/v1/network.go
  crd/apis/network/v1/network_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#518 Move GKENetworkParamSet to v1
  crd/apis/network/v1/gkenetworkparamset_types.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparamset.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparamsetlist.go
  crd/client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  crd/client/network/clientset/versioned/typed/network/v1/generated_expansion.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparamset.go
  crd/client/network/clientset/versioned/typed/network/v1/gkenetworkparamsetlist.go
  crd/client/network/clientset/versioned/typed/network/v1/network_client.go
  crd/client/network/informers/externalversions/generic.go
  crd/client/network/informers/externalversions/network/v1/gkenetworkparamset.go
  crd/client/network/informers/externalversions/network/v1/interface.go
  crd/client/network/listers/network/v1/expansion_generated.go
  crd/client/network/listers/network/v1/gkenetworkparamset.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm

#507 GNP Controller add finalizer on GNP creation & Add Network Name to GNP type.
  cmd/cloud-controller-manager/gkenetworkparamsetcontroller.go
  crd/apis/network/v1alpha1/gkenetworkparamset_types.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
  pkg/controller/gkenetworkparamset/BUILD
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#519 Re-add "register" to update-codegen.sh.
  crd/apis/network/v1/zz_generated.register.go
  crd/hack/generate-groups.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#521 disable gkenetworkparamset controller by default
  cmd/cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#505 Add Network Create and Delete events handling.
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
  pkg/util/controller_utils.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L

#524 fix GKENetworkParamSet CRD
  crd/apis/network/v1alpha1/gkenetworkparamset_types.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test
