Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-02, with the labels that each got.

#456 Introduce DefaultPodNetworkName constant
  crd/apis/network/v1/network.go
  crd/apis/network/v1/network_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#452 Update log-dump.sh
  cluster/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#461 don't replace dependencies inside providers
  providers/go.mod
  providers/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#454 Add GDCE gke-gcloud-auth-plugin support for --impersonate-service-acc…
  cmd/gke-gcloud-auth-plugin/cred.go
  cmd/gke-gcloud-auth-plugin/cred_test.go
  cmd/gke-gcloud-auth-plugin/gcloud_edge_cloud_token_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#434 e2e: add test scenario to test with kOps
  deploy/packages/default/manifest.yaml
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/XL

#471 Update registry k8s.gcr.io -> registry.k8s.io
  cluster/addons/pdcsi-driver/pd-csi.yaml
  cluster/gce/manifests/pdcsi-controller.yaml
  cmd/auth-provider-gcp/provider/provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#474 Add support for CLOUDSDK_AUTH_ACCESS_TOKEN to gke-gcloud-auth-plugin
  cmd/gke-gcloud-auth-plugin/cred.go
  cmd/gke-gcloud-auth-plugin/cred_test.go
  cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#477 Update GCPFirewall CRD
  crd/apis/gcpfirewall/v1beta1/types.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall_client.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall_client.go
  crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/gcpfirewall.go
  crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/interface.go
  crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/expansion_generated.go
  crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go
  crd/config/crds/networking.gke.io_gcpfirewalls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#478 e2e scenario test: Build with workspace
  e2e/add-kubernetes-to-workspace.sh
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/M

#479 bump golang version
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#481 e2e/kops: Get project from boskos
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/M

#465 remove outdated DPDK-UIO option from DeviceModeType
  crd/apis/network/v1alpha1/gkenetworkparamset_types.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#485 Bump go-runner image version to latest patch version.
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#484 Allow binaries to set the base image.
  cmd/gcp-controller-manager/BUILD
  defs/container.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XS
