Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-10, with the labels that each got.

#613 Update readme with information about CCM
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, needs-triage

#617 Add Exponential Backoff on the ListReferrers GCE API calls.
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#620 add tags to cloudbuild job to make it easier to find in the gcp console
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#614 push-images now honors component names in tags
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#623 Skip the VPC validation for XPN clusters in GNP controller
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
  providers/gce/support.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#625 Support owner references that point directly to instanceGroupManagers.
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#619 Don't use SSA in gcp-controller manager PodGC
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
  vendor/k8s.io/kubernetes/pkg/util/pod/BUILD
  vendor/k8s.io/kubernetes/pkg/util/pod/pod.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#626 Add sdmodi to approvers list
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#629 Add vinayakankugoyal to approver list.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#628 Update to golang version 1.20.10
  WORKSPACE
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#624 Bump go mods to use Kubernetes 1.28.2 libraries
  WORKSPACE
  crd/go.mod
  crd/go.sum
  crd/hack/go.mod
  crd/hack/go.sum
  ginko-test-package-version.env
  go.mod
  go.sum
  providers/go.mod
  providers/go.sum
  tools/version.sh
  vendor/github.com/google/cel-go/checker/cost.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/cel/library/cost.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL, needs-triage

#632 Add annotation to disable source mac validation per pod base
  crd/apis/network/v1/annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#633 Rollback PR#598 "Fix ILB deletion by checking for finalizer"
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage
