Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-01, with the labels that each got.

#444 Use k8s.io/cloud-provider-gcp/pkg/clientauthplugin/gcp
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/main.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/BUILD
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/gcp_stub.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#449 bootstrap crd folder, used for networking crds
  crd/OWNERS
  crd/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#446 Changed auth-provider-gcp credentialprovider api to v1
  cluster/gce/gci/configure.sh
  cmd/auth-provider-gcp/app/BUILD
  cmd/auth-provider-gcp/app/getcredentials.go
  cmd/auth-provider-gcp/provider/BUILD
  cmd/auth-provider-gcp/provider/provider.go
  cmd/auth-provider-gcp/provider/provider_test.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/BUILD
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/doc.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/register.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/types.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/zz_generated.conversion.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1/zz_generated.defaults.go
  vendor/k8s.io/kubelet/pkg/apis/credentialprovider/v1alpha1/zz_generated.conversion.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#423 move InterfaceName function to internal component
  crd/apis/network/v1/network.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test
