Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-09, with the labels that each got.

#597 Use LabelTopologyZone rather then deprecated LabelFailureDomainBetaZone
  providers/gce/gce.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
  providers/gce/gce_loadbalancer_utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage

#593 add stderr to returned err from cmd.Run for auth plugin
  cmd/gke-gcloud-auth-plugin/cred.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#599 Simple build scripts for cloud-controller-manager
  .ko.yaml
  tools/common
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#514 Add Taahir Ahmed (ahmedtd) as reviewers and approvers of gcp-controller-manager
  cmd/gcp-controller-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#602 Remove the old DirectPath v1 mode as rollback is no longer needed.
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/hms.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_syncer.go
  cmd/gcp-controller-manager/node_syncer_test.go
  cmd/gcp-controller-manager/sa_map.go
  cmd/gcp-controller-manager/service_account_verifier.go
  cmd/gcp-controller-manager/service_account_verifier_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage

#604 Bump go to 1.20.8
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#600 Use simpler build in cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#598 Fix ILB deletion by checking for finalizer if annotation is removed
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage

#594 Removed unnecessary cidr validation.
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, needs-triage

#606 Register nodeipam controller under canonical name
  cmd/cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#607 cloudAllocator ipv6 only ipam
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/M, needs-triage

#608 ipam: CloudAllocator does not require service or cluster cidr
  cmd/cloud-controller-manager/nodeipamcontroller.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage

#610 gcp-controller: don't make assumptions on PodCIDRs
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage
