Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-12, with the labels that each got.

#634 Add constants to Network CRD
  crd/apis/network/v1/gkenetworkparamset_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#641 Update to go1.20.12
  WORKSPACE
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#644 Update Node pod CIDR in ipam controller for for Multi Pod CIDR suppor…
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/util/node/node.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, ok-to-test, needs-triage

#642 Fix typo in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#647 Add syncDefaultPodRanges change for Multi-networking default Param an…
  cmd/cloud-controller-manager/gkenetworkparamsetcontroller.go
  go.mod
  go.sum
  pkg/controller/gkenetworkparamset/BUILD
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
  providers/gce/gce_fake.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/annotations.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/gkenetworkparamset_types.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider-gcp/crd/client/network/informers/externalversions/factory.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage
