Repository kubernetes/cloud-provider-gcp, pull requests merged in 2023-03, with the labels that each got.

#482 e2e/kops: job fixes
  e2e/scenarios/kops-simple
  test/boskos.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 Migrate `cloud-provider-gcp` resource lock to `leases`
  cmd/gcp-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#473 Support account and project flags in gke-gcloud-auth-plugin
  cmd/gke-gcloud-auth-plugin/cred.go
  cmd/gke-gcloud-auth-plugin/cred_test.go
  cmd/gke-gcloud-auth-plugin/default_credentials_token_provider.go
  cmd/gke-gcloud-auth-plugin/gcloud_edge_cloud_token_provider.go
  cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
  cmd/gke-gcloud-auth-plugin/token_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#493 Revert GCPFirewall CRD back to Cluster scoped
  crd/apis/gcpfirewall/v1beta1/types.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall_client.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go
  crd/client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall_client.go
  crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/gcpfirewall.go
  crd/client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/interface.go
  crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/expansion_generated.go
  crd/client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go
  crd/config/crds/networking.gke.io_gcpfirewalls.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#494 Remove expiry checking from access tokens returned from gcloud tool
  cmd/gke-gcloud-auth-plugin/cred.go
  cmd/gke-gcloud-auth-plugin/cred_test.go
  cmd/gke-gcloud-auth-plugin/gcloud_token_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#492 Adds "device" type network
  crd/apis/network/v1/network_types.go
  crd/apis/network/v1alpha1/network_types.go
  crd/config/crds/networking.gke.io_networks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#497 Extend gceRateLimiter to satisfy cloud.RateLimiter
  providers/gce/support.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#499 Handle missing PodIPv4Ranges in GKENetworkParamSet
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/S, ok-to-test

#500 Add Conditions Field to Network and GKENetworkParamSet
  crd/apis/network/v1/network_types.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/apis/network/v1alpha1/gkenetworkparamset_types.go
  crd/apis/network/v1alpha1/zz_generated.deepcopy.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
  crd/config/crds/networking.gke.io_networks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test
