Repository kubernetes/cloud-provider-gcp, pull requests merged in 2024-05, with the labels that each got.

#676 Update OWNERS for gcp-controller-manager
  cmd/gcp-controller-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#685 Add CLI flag for kubeconfig QPS and burst in gcp-controller-manager
  cmd/gcp-controller-manager/main.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#674 Add OWNERS to gke-gcloud-auth-plugin
  cmd/gke-gcloud-auth-plugin/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#687 Add VM token mode
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/main.go
  cmd/gke-exec-auth-plugin/vm_token.go
Labels: approved, cncf-cla: yes, lgtm, size/M, needs-triage

#688 Add IPAMMode6 field to NetworkSpec
  crd/apis/network/v1/network_types.go
  crd/apis/network/v1/zz_generated.deepcopy.go
  crd/config/crds/networking.gke.io_networks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#689 Order node addresses based on cluster stack type
  providers/gce/gce.go
  providers/gce/gce_fake.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#681 add new RDMA DeviceMode
  crd/apis/network/v1/gkenetworkparamset_types.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#683 Initial e2e test migration from in-tree to gcp cloud provider
  BUILD
  cluster/gce/util.sh
  test/boskos.sh
  test/e2e/firewall.go
  test/e2e/gce.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/loadbalancer.go
  test/e2e/suite_test.go
  tools/run-e2e-test.sh
Labels: size/XXL, approved, cncf-cla: yes, lgtm, triage/accepted

#690 Add VM termination annotation; switch to Compute Beta API
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/node_annotator.go
  cmd/gcp-controller-manager/node_annotator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#700 e2e tests for network tiers
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/network_tiers.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage
