Repository kubernetes/cloud-provider-gcp, pull requests merged in 2024-06, with the labels that each got.

#693 update crd to head in go.mod
  go.mod
  go.sum
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/gkenetworkparamset_types.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/network_types.go
  vendor/k8s.io/cloud-provider-gcp/crd/apis/network/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, triage/accepted

#713 Remove gke-exec-auth-plugin.
  cmd/gke-exec-auth-plugin/BUILD
  cmd/gke-exec-auth-plugin/OWNERS
  cmd/gke-exec-auth-plugin/alt_token_source.go
  cmd/gke-exec-auth-plugin/cache.go
  cmd/gke-exec-auth-plugin/cache_test.go
  cmd/gke-exec-auth-plugin/main.go
  cmd/gke-exec-auth-plugin/request.go
  cmd/gke-exec-auth-plugin/request_test.go
  cmd/gke-exec-auth-plugin/tpm.go
  cmd/gke-exec-auth-plugin/tpm_other.go
  cmd/gke-exec-auth-plugin/tpm_test.go
  cmd/gke-exec-auth-plugin/tpm_windows.go
  cmd/gke-exec-auth-plugin/vm_token.go
  go.mod
  go.sum
  vendor/github.com/gofrs/flock/.gitignore
  vendor/github.com/gofrs/flock/.travis.yml
  vendor/github.com/gofrs/flock/BUILD
  vendor/github.com/gofrs/flock/LICENSE
  vendor/github.com/gofrs/flock/README.md
  vendor/github.com/gofrs/flock/appveyor.yml
  vendor/github.com/gofrs/flock/flock.go
  vendor/github.com/gofrs/flock/flock_unix.go
  vendor/github.com/gofrs/flock/flock_winapi.go
  vendor/github.com/gofrs/flock/flock_windows.go
  vendor/k8s.io/client-go/tools/watch/BUILD
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/k8s.io/client-go/util/certificate/csr/BUILD
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage

#707 Create kustomization in deploy package
  deploy/packages/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#673 Adds OWNERS to auth-provider-gcp
  cmd/auth-provider-gcp/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#360 Fix broken `TestCACacheVerify` test
  cmd/gcp-controller-manager/ca_cache_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#679 L4 ILB - skip nodes from the non default network if multi subnet is t…
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#724 Add NetworkAttachment to GKENetworkParamSet CRD
  crd/apis/network/v1/gkenetworkparamset_types.go
  crd/config/crds/networking.gke.io_gkenetworkparamsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, needs-triage

#730 Remove all GKE specific code from gcp-controller-manager.
  cloudbuild.yaml
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_signer.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
  cmd/gcp-controller-manager/node_csr_approver.go
  cmd/gcp-controller-manager/node_csr_approver_test.go
  go.mod
  go.sum
  pkg/nodeidentity/BUILD
  pkg/nodeidentity/id.go
  pkg/tpmattest/BUILD
  pkg/tpmattest/tpmattest.go
  vendor/github.com/google/go-tpm/LICENSE
  vendor/github.com/google/go-tpm/tpm2/BUILD
  vendor/github.com/google/go-tpm/tpm2/README.md
  vendor/github.com/google/go-tpm/tpm2/constants.go
  vendor/github.com/google/go-tpm/tpm2/error.go
  vendor/github.com/google/go-tpm/tpm2/kdf.go
  vendor/github.com/google/go-tpm/tpm2/open_other.go
  vendor/github.com/google/go-tpm/tpm2/open_windows.go
  vendor/github.com/google/go-tpm/tpm2/structures.go
  vendor/github.com/google/go-tpm/tpm2/tpm2.go
  vendor/github.com/google/go-tpm/tpmutil/BUILD
  vendor/github.com/google/go-tpm/tpmutil/encoding.go
  vendor/github.com/google/go-tpm/tpmutil/poll_other.go
  vendor/github.com/google/go-tpm/tpmutil/poll_unix.go
  vendor/github.com/google/go-tpm/tpmutil/run.go
  vendor/github.com/google/go-tpm/tpmutil/run_other.go
  vendor/github.com/google/go-tpm/tpmutil/run_windows.go
  vendor/github.com/google/go-tpm/tpmutil/structures.go
  vendor/github.com/google/go-tpm/tpmutil/tbs/BUILD
  vendor/github.com/google/go-tpm/tpmutil/tbs/tbs_windows.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage

#732 Remove GKE specific kubelet readonly port signing loop.
  cmd/gcp-controller-manager/BUILD
  cmd/gcp-controller-manager/csr_signer.go
  cmd/gcp-controller-manager/csr_signer_test.go
  cmd/gcp-controller-manager/kubelet_readonly_csr_approver.go
  cmd/gcp-controller-manager/kubelet_readonly_csr_approver_test.go
  cmd/gcp-controller-manager/loops.go
  cmd/gcp-controller-manager/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage

#737 Bump Go version to 1.22.4 (CVE-2024-24790)
  WORKSPACE
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage
