Repository kubernetes/cloud-provider-gcp, pull requests merged in 2024-07, with the labels that each got.

#736 [Cherry-pick #679 to release-1.30] L4 ILB - skip nodes from the non default network if multi subnet is turned on.
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#739 Update gke-networking-api dependency
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/apis/network/v1/gkenetworkparamset_types.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#680 Add another valid container repository to our list.
  providers/gce/gcpcredential/gcpcredential.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#740 Update GNP validations for network attachments
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#745 Cherry-pick #679 to release-1.29
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#747 [Cherrypick #689 to release-1.30] Order node addresses based on clust…
  providers/gce/gce.go
  providers/gce/gce_fake.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#746 [Cherrypick #689 to release-1.29] Order node addresses based on cluster stack type
  providers/gce/gce.go
  providers/gce/gce_fake.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#748 Allow multiple device networks to have the same VPC
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#741 Handle CIDR allocation for network attachments
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, ok-to-test, needs-triage
