Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-06, with the labels that each got.

#856 nodeTopology: de-dup enqueue when there is no label change
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
Labels: approved, cncf-cla: yes, sig/network, size/L, tide/merge-method-squash, needs-triage

#875 Update test/OWNERS
  test/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#873 deps: update deps for patch release 33.1.0
  WORKSPACE
  ginko-test-package-version.env
  go.mod
  go.sum
  providers/go.mod
  providers/go.sum
  test/e2e/go.mod
  test/e2e/go.sum
  tools/version.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage
