Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-03, with the labels that each got.

#808 Add a multiProject option to GCE Cloud Provider
  .gitignore
  cmd/cloud-controller-manager/main.go
  providers/gce/gce.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#814 [Cherry-pick to release-1.32] Add a multiProject option to GCE Cloud Provider
  .gitignore
  cmd/cloud-controller-manager/main.go
  providers/gce/gce.go
  providers/gce/gce_instances.go
  providers/gce/gce_instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, needs-triage

#815 doc: update release instructions, move instructions-how-to-bump-repository to RELEASE.md
  README.md
  docs/RELEASE.md
  docs/instruction-how-to-bump-repository.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/L, needs-triage

#812 Improve CCM listing behavior for GNP object
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#813 Trigger node reconciliation if MultiNetwork info changed
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/util/node/node.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, sig/network, size/L, needs-triage

#817 fix partial multinetwork node patch
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/util/node/node.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, sig/network, size/M, needs-triage

#819 don't run go vet in parallel
  tools/verify-govet.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test, needs-triage

#818 Backport changes to release-1.32
  pkg/controller/gkenetworkparamset/gnpcontroller_validations.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/util/node/node.go
  tools/verify-govet.sh
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, ok-to-test, needs-triage

#820 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#823 OWNERS: add YifeiZhuang
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#824 Handle the node add event in IPAM controller to update the node topology CR
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multi_subnetworks_handler.go
  pkg/controller/nodeipam/ipam/multi_subnetworks_handler_test.go
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
  pkg/util/node/node.go
Labels: approved, cncf-cla: yes, sig/network, size/L, ok-to-test, needs-triage

#825 use docker build to generate images
  Dockerfile
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage
