Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-01, with the labels that each got.

#793 Allow ContainerRegistryProvider to skip Match ContainerRegistryUrls when query the token
  cmd/auth-provider-gcp/provider/provider.go
  cmd/auth-provider-gcp/provider/provider_test.go
  pkg/gcpcredential/gcpcredential.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#795 Bump Go version to 1.23.1 (CVE-2024-34156, CVE-2024-34155, CVE-2024-34158, CVE-2024-24791)
  WORKSPACE
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#797 Remove gcp-controller-manager from tools-push-images
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage
