Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-02, with the labels that each got.

#799 Remove remaining references to the gcp-controller-manager, followup t…
  .ko.yaml
  pkg/csrmetrics/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#798 remove gcp-controller-manager from readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#800 README: fix push image doc, and add push-image tool
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, triage/accepted

#787 add log when a network is skipped due to network-status
  pkg/controller/nodeipam/ipam/multinetwork_cloud_cidr_allocator.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, sig/network, size/XS, needs-triage

#757 Internal Load Balancer Controller do NOT remove nodes with empty string in the zone field
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/M, ok-to-test, needs-triage

#788 avoid GNP deletion when network is refering to it
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller.go
  pkg/controller/gkenetworkparamset/gkenetworkparamset_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage

#806 update version bump instruction, remove the outdated crd directory instructions
  docs/instruction-how-to-bump-repository.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/M, needs-triage

#807 e2e: update path to kOps marker files (1.30 backport)
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#810 Fix cloudbuild tag cause push OSS image job failure
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage
