Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-05, with the labels that each got.

#858 bazel build: use go 1.24 in go_sdk
  WORKSPACE
Labels: approved, cncf-cla: yes, size/XS, tide/merge-method-squash, needs-triage

#860 Revert "[Cherry-pick #834 to release-1.32] Implement loadBalancerClass support for L4 Service selection"
  providers/gce/gce_annotations.go
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_test.go
  providers/gce/gce_loadbalancer_utils_test.go
  providers/gce/gce_util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#861 Revert "[Cherry-pick #826 to release-1.32] Forward individual ports for NetLB with 5 or less service ports"
  cmd/cloud-controller-manager/main.go
  providers/gce/gce.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#862 bazel build: use go 1.24 in go_sdk (1.33 backport)
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash, needs-triage

#865 Fix: Target Pool are leaked when Forwarding Rule fails deletion
  providers/gce/gce_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage
