Repository kubernetes/cloud-provider-gcp, pull requests merged in 2025-04, with the labels that each got.

#826 Forward individual ports for NetLB with 5 or less service ports
  cmd/cloud-controller-manager/main.go
  providers/gce/gce.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#829 fix publish image cloudbuild job failure docker not found, unknown flag: --push
  cloudbuild.yaml
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#828 [Cherry-pick #826 to release-1.32] Forward individual ports for NetLB with 5 or less service ports
  cmd/cloud-controller-manager/main.go
  providers/gce/gce.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#830 use docker build to generate images(1.32 backport)
  Dockerfile
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage

#833 [1.32 backport]fix publish image cloudbuild job failure docker not found, unknown flag: --push
  cloudbuild.yaml
  tools/push-images
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#834 Implement loadBalancerClass support for L4 Service selection
  providers/gce/gce_annotations.go
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_test.go
  providers/gce/gce_loadbalancer_utils_test.go
  providers/gce/gce_util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#840 [Cherry-pick #834 to release-1.32] Implement loadBalancerClass support for L4 Service selection
  providers/gce/gce_annotations.go
  providers/gce/gce_loadbalancer.go
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
  providers/gce/gce_loadbalancer_internal.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_test.go
  providers/gce/gce_loadbalancer_utils_test.go
  providers/gce/gce_util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, ok-to-test, needs-triage

#839 Dockerfile: copy precise dependencies
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#841 chore: remove erroneously comitted vendordiff
  vendordiff.patch
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage

#842 fix: Dockerfile should set entrypoint
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#836 feat(provider/gcp): Add NetLBFinalizerV1 to legacy L4 LB services
  providers/gce/gce_loadbalancer_external.go
  providers/gce/gce_loadbalancer_external_test.go
  providers/gce/gce_loadbalancer_internal_test.go
  providers/gce/gce_loadbalancer_test.go
  providers/gce/gce_loadbalancer_utils_test.go
  providers/gce/gce_util.go
Labels: approved, cncf-cla: yes, lgtm, size/L, ok-to-test, needs-triage

#847 Fix some printf format calls as go 1.24 govet fails if the format str…
  cmd/auth-provider-gcp/main.go
  pkg/clientauthplugin/gcp/gcp_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage

#831 Add nodetopologyCR deletion/reconciling
  pkg/controller/nodeipam/ipam/BUILD
  pkg/controller/nodeipam/ipam/cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/ipam/multi_subnetworks_handler.go
  pkg/controller/nodeipam/ipam/node_topology_syncer.go
  pkg/controller/nodeipam/ipam/node_topology_syncer_test.go
  pkg/controller/nodeipam/ipam/task_queue.go
  pkg/controller/nodeipam/ipam/task_queue_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, sig/network, needs-triage

#848 add feature flag `enable-multi-subnet-cluster` for GKE Multi-Subnet Cluster feature
  cmd/cloud-controller-manager/nodeipamcontroller.go
  cmd/cloud-controller-manager/options/nodeipamcontroller.go
  pkg/controller/nodeipam/config/types.go
  pkg/controller/nodeipam/ipam/cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/controller/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/controller/nodeipam/node_ipam_controller.go
  pkg/controller/nodeipam/node_ipam_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/network, size/L, tide/merge-method-squash, needs-triage

#838 e2e: ensure kops e2e uses push-images script
  Dockerfile
  e2e/add-kubernetes-to-workspace.sh
  e2e/scenarios/kops-simple
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash, needs-triage

#855 fix docker file COPY
  Dockerfile
Labels: approved, cncf-cla: yes, size/XS, needs-triage
